### ISSUE TITLE
Add CSimplePointsMap to CObservation2DRangeScan::writeToMatlab() output

### ISSUE THREAD

**Issue by jesusbriales** [jlblancoc/mrpt#117]
I'm trying to get a CSimplePointsMap object inside the Matlab conversion method
CObservation2DRangeScan::writeToMatlab()
in order to extract the vectors of coordinates x, y and z, with
obs_struct.set("map", map->writeToMatlab());

However, if I include the CSimplePointsHeader in CObservation2DRangeScan.cpp I get the error
.../mrpt/source/libs/obs/src/CObservation2DRangeScan.cpp:20: error: mrpt/maps/CSimplePointsMap.h: No such file or directory
 #include <mrpt/maps/CSimplePointsMap.h>
                                        ^

If I don't do the #include, but add the following lines in CObservation2DRangeScan::writeToMatlab():
const mrpt::maps::CSimplePointsMap *map = this->buildAuxPointsMap<mrpt::maps::CSimplePointsMap>();
obs_struct.set("map", map->writeToMatlab());

I get the following errors:
/home/jesus/Libs/mrpt/source/libs/obs/src/CObservation2DRangeScan.cpp:251: error: invalid use of incomplete type 'const class mrpt::maps::CSimplePointsMap'
  obs_struct.set("map", map->writeToMatlab());
                           ^
/home/jesus/Libs/mrpt/source/libs/obs/include/mrpt/obs/obs_frwds.h:31: error: forward declaration of 'const class mrpt::maps::CSimplePointsMap'
   class CSimplePointsMap;
         ^
/home/jesus/Libs/mrpt/source/libs/obs/include/mrpt/obs/CObservation2DRangeScan.h:117: error: invalid static_cast from type 'mrpt::maps::CMetricMap*' to type 'const mrpt::maps::CSimplePointsMap*'
    return static_cast<const POINTSMAP*>(m_cachedMap.pointer());
                                                              ^

Is there any problem or limitation in using CSimplePointsMaps from the CObservation2DRangeScan class?
Meanwhile I have implemented a workaround in the app code mexgrabber.cpp

**Comment by jlblancoc** [comment]
Sure there is a limitation :-) 
mrpt-maps depends on mrpt-obs, so the opposite cannot be. Dependencies are a directed tree: http://reference.mrpt.org/svn/dot_inline_dotgraph_1.png

So maps can `#include <obs/...>` but not the other way around. 

The point is that for efficency I needed a simple points map inside the 2D laser scan, so I did quite a hack to support that "inverse dependency", but it involves a lot of effort for each independent function you want to support. See: https://github.com/jlblancoc/mrpt/blob/bd9a7c80107b00a67cf7e02e46c89c0582c0271c/libs/obs/src/CObservation2DRangeScan.cpp#L362

However, the cached point cloud should not be serialized: it's not done with ::writeToStream(), so you don't have to do it for mex conversion. In theory is a temporary, internal data field. Also, when a new scan comes from a real laser, the cached map will be empty anyway...

The point is: we might have to define other mex wrappers, like "mrpt.simplepointsmap", with methods like "insert()", etc. but this implies much more thinking, because involves converting mex->mrpt... 
Might be worth anyway, but think of priorities!! ;-)
